### ISSUE TITLE
Time stamp at the Output of the csv report

### ISSUE THREAD

**Issue by LAAP** [CityScope/CSL_Energy#2]
The time doesn't show at the report. The report only gather the last data at cycle 100 instead of the  data of all the 100 cycles

**Comment by agrignard** [comment]
in the code what your are writing is 
````
reflex save_building_attribute when: cycle = 100{
		ask building {
			save [name,time,area,energyPrice,usage,scale, price,nbFloors,production,consumption] to: "../results/buildings1.csv" type:"csv" rewrite: false;
		}
		do pause;
	}
````
which means that when the cycle is equal to 100 all the building attributes are saved at this specific cycle. That's why you see time=100 in the file.

If you want to save at every cycle (I am not sure it is useful and you might have a big file very quickly) you have to write something like
````
	reflex save_building_attribute{
		ask building {
			save [name,time,area,energyPrice,usage,scale, price,nbFloors,production,consumption] to: "../results/buildings1.csv" type:"csv" rewrite: false;
		}
	}
````

If you want to save every 100 cycle just write 

`````
	reflex save_building_attribute when: cycle mod 100 = 0 {
		ask building {
			save [name,time,area,energyPrice,usage,scale, price,nbFloors,production,consumption] to: "../results/buildings1.csv" type:"csv" rewrite: false;
		}
	}
`````
